openapi: 3.0.0
info:
  title: Dashboard API
  version: 1.0.0
  description: API documentation for the dashboard application

servers:
  - url: /api/v1
    description: API v1

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UserProfile:
      type: object
      properties:
        id:
          type: string
        fullName:
          type: string
        avatar:
          type: string
        email:
          type: string
        phone:
          type: string
        location:
          type: string
        timezone:
          type: string
        bio:
          type: string
        socialLinks:
          type: object
          properties:
            twitter:
              type: string
            linkedin:
              type: string
            github:
              type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

paths:
  /users/{id}/profile:
    get:
      summary: Get user profile
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '401':
          description: Unauthorized
        '404':
          description: User not found
        '500':
          description: Internal server error

  /users/{id}/settings:
    post:
      summary: Update user settings
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSettings'
      responses:
        '200':
          description: Settings updated successfully
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '404':
          description: User not found
        '500':
          description: Internal server error

  /users/{id}/preferences:
    put:
      summary: Update user preferences
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPreferences'
      responses:
        '200':
          description: Preferences updated successfully
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '404':
          description: User not found
        '500':
          description: Internal server error

  /users/{id}/sessions:
    delete:
      summary: Delete all user sessions
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Sessions deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: User not found
        '500':
          description: Internal server error
